#!/bin/sh
### BEGIN INIT INFO
# Provides:          lxdm
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop LXDM display manager
# Description:       LXDM is a lightweight display manager for the X11 server
### END INIT INFO

NAME=lxdm
DAEMON=/usr/sbin/lxdm
PIDFILE=/var/run/lxdm.pid
DESC="LXDM Display Manager"

test -x $DAEMON || exit 0


case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON || {
      log_end_msg 1
      exit 1
    }
    log_end_msg 0
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON || {
      log_end_msg 1
      exit 1
    }
    rm -f $PIDFILE
    log_end_msg 0
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting $DESC" "$NAME"
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON "$NAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
