#!/bin/sh
### BEGIN INIT INFO
# Provides:          ntpd
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NTP daemon
### END INIT INFO

DAEMON=/usr/sbin/ntpd
PIDFILE=/var/run/ntpd.pid
DAEMON_OPTS="-g -u ntp:ntp -p $PIDFILE"

case "$1" in
  start)
    echo "Starting ntpd..."
    mkdir -p /var/run
    if [ -x $DAEMON ]; then
      start-stop-daemon --start --quiet \
        --pidfile $PIDFILE --make-pidfile \
        --exec $DAEMON -- $DAEMON_OPTS
      echo "done."
    else
      echo "ntpd binary not found: $DAEMON"
      exit 1
    fi
    ;;
  stop)
    echo "Stopping ntpd..."
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    rm -f $PIDFILE
    echo "done."
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
      echo "ntpd is running (pid $(cat $PIDFILE))"
      exit 0
    else
      echo "ntpd is not running"
      exit 1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0

